
// Code generated by stanc v2.29.0
#include <stan/model/model_header.hpp>
namespace model_ppc_ver2_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 40> locations_array__ = 
{" (found before start of program)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 12, column 4 to column 28)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 13, column 4 to column 27)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 14, column 4 to column 30)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 15, column 4 to column 38)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 16, column 4 to column 36)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 17, column 4 to column 37)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 18, column 4 to column 36)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 24, column 4 to column 25)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 30, column 8 to column 51)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 29, column 19 to line 38, column 5)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 29, column 4 to line 38, column 5)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 70, column 4 to column 29)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 75, column 8 to column 53)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 73, column 19 to line 76, column 5)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 73, column 4 to line 76, column 5)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 45, column 4 to column 36)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 46, column 4 to column 48)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 47, column 4 to column 46)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 48, column 4 to column 43)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 49, column 4 to column 43)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 59, column 8 to column 40)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 60, column 8 to column 40)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 58, column 18 to line 61, column 5)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 58, column 4 to line 61, column 5)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 2, column 4 to column 10)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 3, column 27 to column 28)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 3, column 4 to column 30)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 4, column 11 to column 12)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 4, column 4 to column 32)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 5, column 11 to column 12)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 5, column 4 to column 30)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 6, column 11 to column 12)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 6, column 4 to column 31)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 7, column 11 to column 12)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 7, column 4 to column 30)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 12, column 22 to column 23)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 13, column 21 to column 22)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 24, column 22 to column 23)",
 " (in '/home/racehorse_bayes/models/model_ppc_ver2.stan', line 70, column 11 to column 12)"};




class model_ppc_ver2_model final : public model_base_crtp<model_ppc_ver2_model> {

 private:
  int N;
  std::vector<double> dad_value_numeric;
  Eigen::Matrix<double, -1, 1> dad_num_of_starts__;
  Eigen::Matrix<double, -1, 1> dad_first_place__;
  Eigen::Matrix<double, -1, 1> dad_second_place__;
  Eigen::Matrix<double, -1, 1> dad_third_place__; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> dad_num_of_starts{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> dad_first_place{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> dad_second_place{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> dad_third_place{nullptr, 0};
 
 public:
  ~model_ppc_ver2_model() { }
  
  inline std::string model_name() const final { return "model_ppc_ver2_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.29.0", "stancflags = "};
  }
  
  
  model_ppc_ver2_model(stan::io::var_context& context__,
                       unsigned int random_seed__ = 0,
                       std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "model_ppc_ver2_model_namespace::model_ppc_ver2_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 25;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      
      current_statement__ = 25;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 26;
      stan::math::validate_non_negative_index("dad_value_numeric", "N", N);
      current_statement__ = 27;
      context__.validate_dims("data initialization","dad_value_numeric",
          "double", std::vector<size_t>{static_cast<size_t>(N)});
      dad_value_numeric = 
        std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 27;
      dad_value_numeric = context__.vals_r("dad_value_numeric");
      current_statement__ = 28;
      stan::math::validate_non_negative_index("dad_num_of_starts", "N", N);
      current_statement__ = 29;
      context__.validate_dims("data initialization","dad_num_of_starts",
          "double", std::vector<size_t>{static_cast<size_t>(N)});
      dad_num_of_starts__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      new (&dad_num_of_starts) Eigen::Map<Eigen::Matrix<double, -1, 1>>(dad_num_of_starts__.data(), N);
        
      
      {
        std::vector<local_scalar_t__> dad_num_of_starts_flat__;
        current_statement__ = 29;
        dad_num_of_starts_flat__ = context__.vals_r("dad_num_of_starts");
        current_statement__ = 29;
        pos__ = 1;
        current_statement__ = 29;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 29;
          stan::model::assign(dad_num_of_starts,
            dad_num_of_starts_flat__[(pos__ - 1)],
            "assigning variable dad_num_of_starts", stan::model::index_uni(sym1__));
          current_statement__ = 29;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 30;
      stan::math::validate_non_negative_index("dad_first_place", "N", N);
      current_statement__ = 31;
      context__.validate_dims("data initialization","dad_first_place",
          "double", std::vector<size_t>{static_cast<size_t>(N)});
      dad_first_place__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      new (&dad_first_place) Eigen::Map<Eigen::Matrix<double, -1, 1>>(dad_first_place__.data(), N);
        
      
      {
        std::vector<local_scalar_t__> dad_first_place_flat__;
        current_statement__ = 31;
        dad_first_place_flat__ = context__.vals_r("dad_first_place");
        current_statement__ = 31;
        pos__ = 1;
        current_statement__ = 31;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 31;
          stan::model::assign(dad_first_place,
            dad_first_place_flat__[(pos__ - 1)],
            "assigning variable dad_first_place", stan::model::index_uni(sym1__));
          current_statement__ = 31;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 32;
      stan::math::validate_non_negative_index("dad_second_place", "N", N);
      current_statement__ = 33;
      context__.validate_dims("data initialization","dad_second_place",
          "double", std::vector<size_t>{static_cast<size_t>(N)});
      dad_second_place__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      new (&dad_second_place) Eigen::Map<Eigen::Matrix<double, -1, 1>>(dad_second_place__.data(), N);
        
      
      {
        std::vector<local_scalar_t__> dad_second_place_flat__;
        current_statement__ = 33;
        dad_second_place_flat__ = context__.vals_r("dad_second_place");
        current_statement__ = 33;
        pos__ = 1;
        current_statement__ = 33;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 33;
          stan::model::assign(dad_second_place,
            dad_second_place_flat__[(pos__ - 1)],
            "assigning variable dad_second_place", stan::model::index_uni(sym1__));
          current_statement__ = 33;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 34;
      stan::math::validate_non_negative_index("dad_third_place", "N", N);
      current_statement__ = 35;
      context__.validate_dims("data initialization","dad_third_place",
          "double", std::vector<size_t>{static_cast<size_t>(N)});
      dad_third_place__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      new (&dad_third_place) Eigen::Map<Eigen::Matrix<double, -1, 1>>(dad_third_place__.data(), N);
        
      
      {
        std::vector<local_scalar_t__> dad_third_place_flat__;
        current_statement__ = 35;
        dad_third_place_flat__ = context__.vals_r("dad_third_place");
        current_statement__ = 35;
        pos__ = 1;
        current_statement__ = 35;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 35;
          stan::model::assign(dad_third_place,
            dad_third_place_flat__[(pos__ - 1)],
            "assigning variable dad_third_place", stan::model::index_uni(sym1__));
          current_statement__ = 35;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 36;
      stan::math::validate_non_negative_index("a0", "N", N);
      current_statement__ = 37;
      stan::math::validate_non_negative_index("a1", "N", N);
      current_statement__ = 38;
      stan::math::validate_non_negative_index("mu", "N", N);
      current_statement__ = 39;
      stan::math::validate_non_negative_index("kid_value_pred", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = N + N + 1 + 1 + 1 + 1 + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "model_ppc_ver2_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<local_scalar_t__, -1, 1> a0 =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 1;
      a0 = in__.template read_constrain_lb<
             Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(0, lp__, N);
      Eigen::Matrix<local_scalar_t__, -1, 1> a1 =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 2;
      a1 = in__.template read_constrain_lb<
             Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(0, lp__, N);
      local_scalar_t__ value_coeff = DUMMY_VAR__;
      current_statement__ = 3;
      value_coeff = in__.template read_constrain_lb<local_scalar_t__, 
                      jacobian__>(0, lp__);
      local_scalar_t__ num_of_starts_coeff = DUMMY_VAR__;
      current_statement__ = 4;
      num_of_starts_coeff = in__.template read_constrain_lb<local_scalar_t__, 
                              jacobian__>(0, lp__);
      local_scalar_t__ first_place_coeff = DUMMY_VAR__;
      current_statement__ = 5;
      first_place_coeff = in__.template read_constrain_lb<local_scalar_t__, 
                            jacobian__>(0, lp__);
      local_scalar_t__ second_place_coeff = DUMMY_VAR__;
      current_statement__ = 6;
      second_place_coeff = in__.template read_constrain_lb<local_scalar_t__, 
                             jacobian__>(0, lp__);
      local_scalar_t__ third_place_coeff = DUMMY_VAR__;
      current_statement__ = 7;
      third_place_coeff = in__.template read_constrain_lb<local_scalar_t__, 
                            jacobian__>(0, lp__);
      std::vector<local_scalar_t__> mu =
         std::vector<local_scalar_t__>(N, DUMMY_VAR__);
      current_statement__ = 11;
      for (int j = 1; j <= N; ++j) {
        current_statement__ = 9;
        stan::model::assign(mu,
          (value_coeff *
            stan::model::rvalue(dad_value_numeric, "dad_value_numeric",
              stan::model::index_uni(j))),
          "assigning variable mu", stan::model::index_uni(j));
      }
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "mu", mu, 0);
      {
        current_statement__ = 16;
        lp_accum__.add(
          stan::math::exponential_lpdf<propto__>(value_coeff, 2.37));
        current_statement__ = 17;
        lp_accum__.add(
          stan::math::lognormal_lpdf<propto__>(num_of_starts_coeff, -1.48,
            0.71));
        current_statement__ = 18;
        lp_accum__.add(
          stan::math::lognormal_lpdf<propto__>(first_place_coeff, -1.40,
            0.59));
        current_statement__ = 19;
        lp_accum__.add(
          stan::math::exponential_lpdf<propto__>(second_place_coeff, 3.59));
        current_statement__ = 20;
        lp_accum__.add(
          stan::math::exponential_lpdf<propto__>(third_place_coeff, 6.10));
        current_statement__ = 24;
        for (int j = 1; j <= N; ++j) {
          current_statement__ = 21;
          lp_accum__.add(
            stan::math::lognormal_lpdf<propto__>(
              stan::model::rvalue(a0, "a0", stan::model::index_uni(j)),
              -4.951, 0.83));
          current_statement__ = 22;
          lp_accum__.add(
            stan::math::lognormal_lpdf<propto__>(
              stan::model::rvalue(a1, "a1", stan::model::index_uni(j)),
              -4.951, 0.83));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "model_ppc_ver2_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<double, -1, 1> a0 =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      a0 = in__.template read_constrain_lb<
             Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(0, lp__, N);
      Eigen::Matrix<double, -1, 1> a1 =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      a1 = in__.template read_constrain_lb<
             Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(0, lp__, N);
      double value_coeff = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      value_coeff = in__.template read_constrain_lb<local_scalar_t__, 
                      jacobian__>(0, lp__);
      double num_of_starts_coeff = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      num_of_starts_coeff = in__.template read_constrain_lb<local_scalar_t__, 
                              jacobian__>(0, lp__);
      double first_place_coeff = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      first_place_coeff = in__.template read_constrain_lb<local_scalar_t__, 
                            jacobian__>(0, lp__);
      double second_place_coeff = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      second_place_coeff = in__.template read_constrain_lb<local_scalar_t__, 
                             jacobian__>(0, lp__);
      double third_place_coeff = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      third_place_coeff = in__.template read_constrain_lb<local_scalar_t__, 
                            jacobian__>(0, lp__);
      std::vector<double> mu =
         std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      out__.write(a0);
      out__.write(a1);
      out__.write(value_coeff);
      out__.write(num_of_starts_coeff);
      out__.write(first_place_coeff);
      out__.write(second_place_coeff);
      out__.write(third_place_coeff);
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 11;
      for (int j = 1; j <= N; ++j) {
        current_statement__ = 9;
        stan::model::assign(mu,
          (value_coeff *
            stan::model::rvalue(dad_value_numeric, "dad_value_numeric",
              stan::model::index_uni(j))),
          "assigning variable mu", stan::model::index_uni(j));
      }
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "mu", mu, 0);
      if (emit_transformed_parameters__) {
        out__.write(mu);
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, 1> kid_value_pred =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 15;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 13;
        stan::model::assign(kid_value_pred,
          stan::math::exponential_rng(
            (1 / stan::model::rvalue(mu, "mu", stan::model::index_uni(i))),
            base_rng__),
          "assigning variable kid_value_pred", stan::model::index_uni(i));
      }
      out__.write(kid_value_pred);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__, -1, 1> a0 =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(N, DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        stan::model::assign(a0, in__.read<local_scalar_t__>(),
          "assigning variable a0", stan::model::index_uni(sym1__));
      }
      out__.write_free_lb(0, a0);
      Eigen::Matrix<local_scalar_t__, -1, 1> a1 =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(N, DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        stan::model::assign(a1, in__.read<local_scalar_t__>(),
          "assigning variable a1", stan::model::index_uni(sym1__));
      }
      out__.write_free_lb(0, a1);
      local_scalar_t__ value_coeff = DUMMY_VAR__;
      value_coeff = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, value_coeff);
      local_scalar_t__ num_of_starts_coeff = DUMMY_VAR__;
      num_of_starts_coeff = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, num_of_starts_coeff);
      local_scalar_t__ first_place_coeff = DUMMY_VAR__;
      first_place_coeff = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, first_place_coeff);
      local_scalar_t__ second_place_coeff = DUMMY_VAR__;
      second_place_coeff = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, second_place_coeff);
      local_scalar_t__ third_place_coeff = DUMMY_VAR__;
      third_place_coeff = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, third_place_coeff);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"a0", "a1", "value_coeff",
      "num_of_starts_coeff", "first_place_coeff", "second_place_coeff",
      "third_place_coeff", "mu", "kid_value_pred"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{
                                                                   static_cast<size_t>(N)
                                                                   },
      std::vector<size_t>{static_cast<size_t>(N)}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "a0" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "a1" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "value_coeff");
    param_names__.emplace_back(std::string() + "num_of_starts_coeff");
    param_names__.emplace_back(std::string() + "first_place_coeff");
    param_names__.emplace_back(std::string() + "second_place_coeff");
    param_names__.emplace_back(std::string() + "third_place_coeff");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "kid_value_pred" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "a0" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "a1" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "value_coeff");
    param_names__.emplace_back(std::string() + "num_of_starts_coeff");
    param_names__.emplace_back(std::string() + "first_place_coeff");
    param_names__.emplace_back(std::string() + "second_place_coeff");
    param_names__.emplace_back(std::string() + "third_place_coeff");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "kid_value_pred" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"a0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"a1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"value_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"num_of_starts_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"first_place_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"second_place_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"third_place_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"kid_value_pred\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"a0\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"a1\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"value_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"num_of_starts_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"first_place_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"second_place_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"third_place_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"kid_value_pred\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((((((N + N) + 1) + 1) + 1) + 1) + 1);
      const size_t num_transformed = N;
      const size_t num_gen_quantities = N;
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((((((N + N) + 1) + 1) + 1) + 1) + 1);
      const size_t num_transformed = N;
      const size_t num_gen_quantities = N;
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 7> names__{"a0", "a1", "value_coeff",
      "num_of_starts_coeff", "first_place_coeff", "second_place_coeff",
      "third_place_coeff"};
      const std::array<Eigen::Index, 7> constrain_param_sizes__{N, N, 
       1, 1, 1, 1, 1};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}
using stan_model = model_ppc_ver2_model_namespace::model_ppc_ver2_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return model_ppc_ver2_model_namespace::profiles__;
}

#endif


