
// Code generated by stanc v2.29.0
#include <stan/model/model_header.hpp>
namespace model2_basic_v2_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 21> locations_array__ = 
{" (found before start of program)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 4, column 4 to column 64)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 5, column 4 to column 51)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 6, column 4 to column 63)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 7, column 4 to column 61)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 8, column 4 to column 57)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 9, column 4 to column 56)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 10, column 4 to column 52)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 11, column 4 to column 52)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 13, column 4 to column 56)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 14, column 4 to column 63)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 15, column 4 to column 60)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 16, column 4 to column 62)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 17, column 4 to column 61)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 18, column 4 to column 73)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 19, column 4 to column 74)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 21, column 4 to line 25, column 63)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 27, column 4 to column 50)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 29, column 4 to column 102)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 30, column 4 to column 78)",
 " (in '/home/racehorse_bayes/models/model2_basic_v2.stan', line 32, column 4 to column 52)"};




class model2_basic_v2_model final : public model_base_crtp<model2_basic_v2_model> {

 private:
   
  
 
 public:
  ~model2_basic_v2_model() { }
  
  inline std::string model_name() const final { return "model2_basic_v2_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.29.0", "stancflags = "};
  }
  
  
  model2_basic_v2_model(stan::io::var_context& context__,
                        unsigned int random_seed__ = 0,
                        std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "model2_basic_v2_model_namespace::model2_basic_v2_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 0U;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "model2_basic_v2_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "model2_basic_v2_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      double potential_rich = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      potential_rich = stan::math::bernoulli_rng(0.05, base_rng__);
      double value = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      value = stan::math::exponential_rng(2.37, base_rng__);
      double num_of_starts = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      num_of_starts = stan::math::lognormal_rng(-1.48, 0.71, base_rng__);
      double first_place = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      first_place = stan::math::lognormal_rng(-1.40, 0.59, base_rng__);
      double second_place = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      second_place = stan::math::exponential_rng(3.59, base_rng__);
      double third_place = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      third_place = stan::math::exponential_rng(6.10, base_rng__);
      double a0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      a0 = stan::math::lognormal_rng(-1.95, 0.83, base_rng__);
      double a1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 8;
      a1 = stan::math::lognormal_rng(-1.95, 0.83, base_rng__);
      double value_coeff = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 9;
      value_coeff = stan::math::normal_rng(0.2, 0.01, base_rng__);
      double num_of_starts_coeff = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 10;
      num_of_starts_coeff = stan::math::normal_rng(0.4, 0.01, base_rng__);
      double first_place_coeff = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 11;
      first_place_coeff = stan::math::normal_rng(0.3, 0.01, base_rng__);
      double second_place_coeff = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 12;
      second_place_coeff = stan::math::normal_rng(0.3, 0.01, base_rng__);
      double third_place_coeff = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 13;
      third_place_coeff = stan::math::normal_rng(0.3, 0.01, base_rng__);
      double potential_rich_mulog_coeff =
         std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 14;
      potential_rich_mulog_coeff = stan::math::normal_rng(0.05, 0.001,
                                     base_rng__);
      double potential_rich_sigmalog_coeff =
         std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 15;
      potential_rich_sigmalog_coeff = stan::math::normal_rng(0.1, 0.01,
                                        base_rng__);
      double mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 16;
      mu = (stan::math::fmax(
              ((((((((value_coeff * value) + a0) - a1) +
                    (num_of_starts_coeff * num_of_starts)) +
                   (first_place_coeff * first_place)) +
                  (second_place_coeff * second_place)) +
                 (third_place_coeff * third_place)) / 4), 0) + 0.003);
      double sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 17;
      sigma = stan::math::normal_rng(0.1, 0.01, base_rng__);
      double mulog = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 18;
      mulog = (((1 - potential_rich) *
                 stan::math::log(
                   (stan::math::pow(mu, 2) /
                     stan::math::sqrt(
                       (stan::math::pow(mu, 2) + stan::math::pow(sigma, 2))))))
                + (potential_rich * 0.05));
      double sigmalog = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 19;
      sigmalog = (((1 - potential_rich) *
                    stan::math::normal_rng(1, 0.1, base_rng__)) +
                   (potential_rich * 0.1));
      double kid_value = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 20;
      kid_value = stan::math::lognormal_rng(mulog, sigmalog, base_rng__);
      current_statement__ = 1;
      stan::math::check_greater_or_equal(function__, "potential_rich",
                                            potential_rich, 0);
      current_statement__ = 1;
      stan::math::check_less_or_equal(function__, "potential_rich",
                                         potential_rich, 1);
      current_statement__ = 2;
      stan::math::check_greater_or_equal(function__, "value", value, 0.0);
      current_statement__ = 3;
      stan::math::check_greater_or_equal(function__, "num_of_starts",
                                            num_of_starts, 0.0);
      current_statement__ = 4;
      stan::math::check_greater_or_equal(function__, "first_place",
                                            first_place, 0.0);
      current_statement__ = 5;
      stan::math::check_greater_or_equal(function__, "second_place",
                                            second_place, 0.0);
      current_statement__ = 6;
      stan::math::check_greater_or_equal(function__, "third_place",
                                            third_place, 0.0);
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "a0", a0, 0.0);
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "a1", a1, 0.0);
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "value_coeff",
                                            value_coeff, 0.0);
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "num_of_starts_coeff",
                                            num_of_starts_coeff, 0.0);
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "first_place_coeff",
                                            first_place_coeff, 0.0);
      current_statement__ = 12;
      stan::math::check_greater_or_equal(function__, "second_place_coeff",
                                            second_place_coeff, 0.0);
      current_statement__ = 13;
      stan::math::check_greater_or_equal(function__, "third_place_coeff",
                                            third_place_coeff, 0.0);
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "potential_rich_mulog_coeff",
                                            potential_rich_mulog_coeff, 0.0);
      current_statement__ = 15;
      stan::math::check_greater_or_equal(function__, "potential_rich_sigmalog_coeff",
                                            potential_rich_sigmalog_coeff,
                                            0.0);
      current_statement__ = 16;
      stan::math::check_greater_or_equal(function__, "mu", mu, 0);
      current_statement__ = 17;
      stan::math::check_greater_or_equal(function__, "sigma", sigma, 0.0);
      out__.write(potential_rich);
      out__.write(value);
      out__.write(num_of_starts);
      out__.write(first_place);
      out__.write(second_place);
      out__.write(third_place);
      out__.write(a0);
      out__.write(a1);
      out__.write(value_coeff);
      out__.write(num_of_starts_coeff);
      out__.write(first_place_coeff);
      out__.write(second_place_coeff);
      out__.write(third_place_coeff);
      out__.write(potential_rich_mulog_coeff);
      out__.write(potential_rich_sigmalog_coeff);
      out__.write(mu);
      out__.write(sigma);
      out__.write(mulog);
      out__.write(sigmalog);
      out__.write(kid_value);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"potential_rich", "value",
      "num_of_starts", "first_place", "second_place", "third_place", "a0",
      "a1", "value_coeff", "num_of_starts_coeff", "first_place_coeff",
      "second_place_coeff", "third_place_coeff",
      "potential_rich_mulog_coeff", "potential_rich_sigmalog_coeff", "mu",
      "sigma", "mulog", "sigmalog", "kid_value"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "potential_rich");
      param_names__.emplace_back(std::string() + "value");
      param_names__.emplace_back(std::string() + "num_of_starts");
      param_names__.emplace_back(std::string() + "first_place");
      param_names__.emplace_back(std::string() + "second_place");
      param_names__.emplace_back(std::string() + "third_place");
      param_names__.emplace_back(std::string() + "a0");
      param_names__.emplace_back(std::string() + "a1");
      param_names__.emplace_back(std::string() + "value_coeff");
      param_names__.emplace_back(std::string() + "num_of_starts_coeff");
      param_names__.emplace_back(std::string() + "first_place_coeff");
      param_names__.emplace_back(std::string() + "second_place_coeff");
      param_names__.emplace_back(std::string() + "third_place_coeff");
      param_names__.emplace_back(std::string() + "potential_rich_mulog_coeff");
      param_names__.emplace_back(std::string() + "potential_rich_sigmalog_coeff");
      param_names__.emplace_back(std::string() + "mu");
      param_names__.emplace_back(std::string() + "sigma");
      param_names__.emplace_back(std::string() + "mulog");
      param_names__.emplace_back(std::string() + "sigmalog");
      param_names__.emplace_back(std::string() + "kid_value");
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "potential_rich");
      param_names__.emplace_back(std::string() + "value");
      param_names__.emplace_back(std::string() + "num_of_starts");
      param_names__.emplace_back(std::string() + "first_place");
      param_names__.emplace_back(std::string() + "second_place");
      param_names__.emplace_back(std::string() + "third_place");
      param_names__.emplace_back(std::string() + "a0");
      param_names__.emplace_back(std::string() + "a1");
      param_names__.emplace_back(std::string() + "value_coeff");
      param_names__.emplace_back(std::string() + "num_of_starts_coeff");
      param_names__.emplace_back(std::string() + "first_place_coeff");
      param_names__.emplace_back(std::string() + "second_place_coeff");
      param_names__.emplace_back(std::string() + "third_place_coeff");
      param_names__.emplace_back(std::string() + "potential_rich_mulog_coeff");
      param_names__.emplace_back(std::string() + "potential_rich_sigmalog_coeff");
      param_names__.emplace_back(std::string() + "mu");
      param_names__.emplace_back(std::string() + "sigma");
      param_names__.emplace_back(std::string() + "mulog");
      param_names__.emplace_back(std::string() + "sigmalog");
      param_names__.emplace_back(std::string() + "kid_value");
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"potential_rich\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"value\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"num_of_starts\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"first_place\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"second_place\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"third_place\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"a0\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"a1\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"value_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"num_of_starts_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"first_place_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"second_place_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"third_place_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"potential_rich_mulog_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"potential_rich_sigmalog_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"mulog\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigmalog\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"kid_value\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"potential_rich\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"value\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"num_of_starts\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"first_place\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"second_place\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"third_place\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"a0\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"a1\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"value_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"num_of_starts_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"first_place_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"second_place_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"third_place_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"potential_rich_mulog_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"potential_rich_sigmalog_coeff\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"mulog\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigmalog\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"kid_value\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 0;
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 
  (((((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)
           + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1);
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 0;
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 
  (((((((((((((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1)
           + 1) + 1) + 1) + 1) + 1) + 1) + 1) + 1);
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 0> names__{};
      const std::array<Eigen::Index, 0> constrain_param_sizes__{};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}
using stan_model = model2_basic_v2_model_namespace::model2_basic_v2_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return model2_basic_v2_model_namespace::profiles__;
}

#endif


